train:
  name: "DQN_normiert_small_observationspace_corrected_padding"
  dir: "/home/group1/workspace/data"
  
  timesteps: 10000
  resetTimesteps: False 
  policy: "MlpPolicy"
  DQN:
    gamma: 0.99
    learning_rate: 1e-4
    buffer_size: 100000
    batch_size: 64
    train_freq: 4
    target_update_intervall: 1000
    exploration_fraction: 0.1
    exploration_final_eps: 0.02
    verbose: 1
env:
  actions: 4
  render: True
  assetsPath: "/home/group1/workspace/assets"
  maxSteps: 200
  colours: ["red", "green"]
  objects:
    number: 3
    dirs: ["signs", "cubes"]
    parts: ["plus", "cube"]
    states: 3
  goals:
    states: 3  
  robot:
    states: 2
